nginx:
    build: ./Docker-nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./Docker-node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        - ./Docker-node/:/home/app
        - /home/app/node_modules
node2:
    build: ./Docker-node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        - ./Docker-node/:/home/app
        - /home/app/node_modules
node3:
    build: ./Docker-node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        - ./Docker-node/:/home/app
        - /home/app/node_modules
redis:
    image: redis
    ports:
        - "6379"